version: "3.9"

services:
  auth:
    build:
      context: ./fastapi-oauth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi-oauth/.env
    volumes:
      - ./fastapi-oauth/secrets:/app/secrets:ro
    restart: unless-stopped
  cuentas:
    build:
      context: ./cuentas-service
      dockerfile: Dockerfile
    ports:
      - "8013:8013"
    env_file:
      - ./cuentas-service/.env
    volumes:
      - ./cuentas-service/secrets:/app/secrets:ro
    restart: unless-stopped
    
  pagos-service:
    build:
      context: ./pagos_service
      dockerfile: Dockerfile
    container_name: pagos-service
    ports:
      - "8003:8003"
    environment:
    USE_FIRESTORE: "true"
    FIREBASE_CREDENTIALS_PATH: "/app/firebase-key.json"
    volumes:
      - ./firebase-key.json:/app/firebase-key.json:ro
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
