version: "3.9"

services:
  auth:
    build:
      context: ./fastapi-oauth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi-oauth/.env
    volumes:
      - ./fastapi-oauth/secrets:/app/secrets:ro
    restart: unless-stopped
  cuentas:
    build:
      context: ./cuentas-service
      dockerfile: Dockerfile
    ports:
      - "8013:8013"
    env_file:
      - ./cuentas-service/.env
    volumes:
      - ./cuentas-service/secrets:/app/secrets:ro
    restart: unless-stopped
    networks:
      - micro-net
 
networks:
  micro-net:
    driver: bridge
